### ISSUE TITLE
rviz_plugin_tutorials build failed with boost 1.57 on OS X Yosemite

### ISSUE THREAD

**Issue by chien800614** [ros-visualization/visualization_tutorials#23]
I'm trying to build rviz_plugin_tutorials on OS X Yosemite, and fails the message:

Call Stack (most recent call first):
  /Users/install_isolated/share/urdf/cmake/urdfConfig.cmake:165 (find_package)
  /Users/install_isolated/share/rviz/cmake/rvizConfig.cmake:165 (find_package)
  /Users/install_isolated/share/catkin/cmake/catkinConfig.cmake:75 (find_package)
  CMakeLists.txt:7 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - not found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - found
-- Looking for QT_MAC_USE_COCOA
-- Looking for QT_MAC_USE_COCOA - found
-- Found Qt4: /usr/local/bin/qmake (found version "4.8.6") 
-- Configuring done

CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   rviz_plugin_tutorials

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/build_isolated/rviz_plugin_tutorials
==> make -j4 -l4 in '/Users/build_isolated/rviz_plugin_tutorials'
[  7%] [ 15%] [ 23%] [ 30%] Generating src/moc_teleop_panel.cxx
Generating src/moc_drive_widget.cxx
Generating src/moc_imu_display.cxx
Generating src/moc_plant_flag_tool.cxx
usr/local/Cellar/boost/1.57.0/include/boost/type_traits/detail/has_binary_operator.hp:50: Parse error at "BOOST_JOIN"
make[2]: **\* [src/moc_imu_display.cxx] Error 1
make[1]: **\* [CMakeFiles/rviz_plugin_tutorials.dir/all] Error 2
make: **\* [all] Error 2
<== Failed to process package 'rviz_plugin_tutorials': 
  Command '/Users/install_isolated/env.sh make -j4 -l4' returned non-zero exit status 2

**Comment by wjwwood** [comment]
Resolved by #22.
