### ISSUE TITLE
rviz_plugin_tutorials fails to compile on OS X

### ISSUE THREAD

**Issue by wjwwood** [ros-visualization/visualization_tutorials#3]
See:

http://answers.ros.org/question/56553/rosmake-fails-on-os-x/
http://pastie.org/pastes/6368348/text

The failure:

```
{-------------------------------------------------------------------------------
  -- Looking for Q_WS_MAC
  -- Looking for Q_WS_MAC - found
  -- Looking for QT_MAC_USE_COCOA
  -- Looking for QT_MAC_USE_COCOA - found
  -- Found Qt4: /usr/local/bin/qmake (found version "4.8.4") 
  [rosbuild] Couldn't find source file /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials/build/src/moc_drive_widget.cxx; assuming that it is in /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials and will be generated later
  [rosbuild] Couldn't find source file /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials/build/src/moc_imu_display.cxx; assuming that it is in /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials and will be generated later
  [rosbuild] Couldn't find source file /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials/build/src/moc_plant_flag_tool.cxx; assuming that it is in /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials and will be generated later
  [rosbuild] Couldn't find source file /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials/build/src/moc_teleop_panel.cxx; assuming that it is in /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials and will be generated later
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials/build
  cd build && make -j -l8
  Scanning dependencies of target rospack_genmsg_libexe
  [  0%] Built target rospack_genmsg_libexe
  Scanning dependencies of target rosbuild_precompile
  [  0%] Built target rosbuild_precompile
  [  7%] Generating src/moc_teleop_panel.cxx
  [ 15%] Generating src/moc_plant_flag_tool.cxx
  [ 23%] Generating src/moc_imu_display.cxx
  [ 30%] Generating src/moc_drive_widget.cxx
  Scanning dependencies of target rviz_plugin_tutorials
  [ 38%] Building CXX object CMakeFiles/rviz_plugin_tutorials.dir/src/drive_widget.cpp.o
  /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials/src/drive_widget.cpp:113:23: error: variable length array of non-POD element type 'QPointF'
      QPointF left_track[ step_count ];
                        ^
  /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials/src/drive_widget.cpp:114:24: error: variable length array of non-POD element type 'QPointF'
      QPointF right_track[ step_count ];
                         ^
  In file included from /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials/src/drive_widget.cpp:34:
  In file included from /usr/local/Cellar/qt/4.8.4/include/QtGui/QMouseEvent:1:
  In file included from /usr/local/Cellar/qt/4.8.4/include/QtGui/qevent.h:52:
  /usr/local/Cellar/qt/4.8.4/include/QtGui/qmime.h:119:10: warning: private field 'type' is not used [-Wunused-private-field]
      char type;
           ^
  1 warning and 2 errors generated.
  make[3]: *** [CMakeFiles/rviz_plugin_tutorials.dir/src/drive_widget.cpp.o] Error 1
  make[2]: *** [CMakeFiles/rviz_plugin_tutorials.dir/all] Error 2
  make[1]: *** [all] Error 2
-------------------------------------------------------------------------------}
[ rosmake ] Output from build of package rviz_plugin_tutorials written to:
[ rosmake ]    /Users/alex/.ros/rosmake/rosmake_output-20130302-173409/rviz_plugin_tutorials/build_output.log
[rosmake-3] Finished <<< rviz_plugin_tutorials [FAIL] [ 25.69 seconds ]
```

I do not have the full error log, but perhaps someone could update the ticket with that.

**Comment by alexreg** [comment]
Surely you've just linked to the full error log (which I posted on answers.ros.org) in that very post? i.e. http://pastie.org/pastes/6368348/text

**Comment by wjwwood** [comment]
@alexreg Most of the relavent error is in my link, but rosmake truncates errors, you would need to post the full build log from the log file which rosmake references.

**Comment by wjwwood** [comment]
See:

```
[ rosmake ] Output from build of package rviz_plugin_tutorials written to:
[ rosmake ]    /Users/alex/.ros/rosmake/rosmake_output-20130302-173409/rviz_plugin_tutorials/build_output.log
```

**Comment by alexreg** [comment]
Okay, here's the contents of `rviz_plugin_tutorials/build_output.log`.

<pre>
mkdir -p bin
cd build && cmake -Wdev -DCMAKE_TOOLCHAIN_FILE=/opt/ros/groovy/share/ros/core/rosbuild/rostoolchain.cmake  ..
-- The C compiler identification is Clang 4.2.0
-- The CXX compiler identification is Clang 4.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.2") 
[rosbuild] Building package rviz_plugin_tutorials
[rosbuild] Cached build flags older than manifests; calling rospack to get flags
-- Using CATKIN_DEVEL_PREFIX: /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/groovy
-- This workspace overlays: /opt/ros/groovy
-- Found PY_em: /usr/local/lib/python2.7/site-packages/em.pyc  
-- Found gtest: gtests will be built
-- catkin 0.5.63
[rosbuild] Including /opt/ros/groovy/share/roscpp/rosbuild/roscpp.cmake
[rosbuild] Including /opt/ros/groovy/share/rospy/rosbuild/rospy.cmake
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - not found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - found
-- Looking for QT_MAC_USE_COCOA
-- Looking for QT_MAC_USE_COCOA - found
-- Found Qt4: /usr/local/bin/qmake (found version "4.8.4") 
[rosbuild] Couldn't find source file /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials/build/src/moc_drive_widget.cxx; assuming that it is in /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials and will be generated later
[rosbuild] Couldn't find source file /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials/build/src/moc_imu_display.cxx; assuming that it is in /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials and will be generated later
[rosbuild] Couldn't find source file /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials/build/src/moc_plant_flag_tool.cxx; assuming that it is in /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials and will be generated later
[rosbuild] Couldn't find source file /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials/build/src/moc_teleop_panel.cxx; assuming that it is in /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials and will be generated later
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials/build
cd build && make -j -l8
Scanning dependencies of target rospack_genmsg_libexe
[  0%] Built target rospack_genmsg_libexe
Scanning dependencies of target rosbuild_precompile
[  0%] Built target rosbuild_precompile
[  7%] Generating src/moc_teleop_panel.cxx
[ 15%] Generating src/moc_plant_flag_tool.cxx
[ 23%] Generating src/moc_imu_display.cxx
[ 30%] Generating src/moc_drive_widget.cxx
Scanning dependencies of target rviz_plugin_tutorials
[ 38%] Building CXX object CMakeFiles/rviz_plugin_tutorials.dir/src/drive_widget.cpp.o
/Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials/src/drive_widget.cpp:113:23: error: variable length array of non-POD element type 'QPointF'
    QPointF left_track[ step_count ];
                      ^
/Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials/src/drive_widget.cpp:114:24: error: variable length array of non-POD element type 'QPointF'
    QPointF right_track[ step_count ];
                       ^
In file included from /Users/alex/ros_ws/visualization_tutorials/rviz_plugin_tutorials/src/drive_widget.cpp:34:
In file included from /usr/local/Cellar/qt/4.8.4/include/QtGui/QMouseEvent:1:
In file included from /usr/local/Cellar/qt/4.8.4/include/QtGui/qevent.h:52:
/usr/local/Cellar/qt/4.8.4/include/QtGui/qmime.h:119:10: warning: private field 'type' is not used [-Wunused-private-field]
    char type;
         ^
1 warning and 2 errors generated.
make[3]: *** [CMakeFiles/rviz_plugin_tutorials.dir/src/drive_widget.cpp.o] Error 1
make[2]: *** [CMakeFiles/rviz_plugin_tutorials.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2
 </pre>

**Comment by dgossow** [comment]
This uses a non-standard C++ extension that clang doesn't support (a variable-length array of QPoint, which is a class). You can fix this by using a vector or making step_count a constant expression.

**Comment by alexreg** [comment]
Ah right. Thanks for that! Hopefully this can be fixed soon. :-)
