### ISSUE TITLE
Lunar Release

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-visualization/visualization_tutorials#37]
Hi @wjwwood and visualization_tutorials maintainers!

We are reaching the beta testing phase of ROS Lunar in a few days :tada:  and this package is one of the last one [blocking the release of desktop_full](http://repositories.ros.org/status_page/blocked_releases_lunar.html?q=id%3D%22metapackages%22&s=6&r=1). Please consider making a release as soon as possible and if you don't have time to make a release you can release the current kinetic version by running `bloom-release visualization_tutorials -r lunar -t lunar -n`

**Comment by wjwwood** [comment]
I was just doing that: https://github.com/ros/rosdistro/pull/14689

The `-n` shouldn't be necessary 😄.

I'll close in since https://github.com/ros/rosdistro/pull/14689 is tracking this now.

**Comment by mikaelarguedas** [comment]
Thanks @wjwwood for the  :rocket: fast release!
