### ISSUE TITLE
Non-normalized rotation quaternions in interactive marker tutorial

### ISSUE THREAD

**Issue by Martin-Oehler** [ros-visualization/visualization_tutorials#38]
The [interactive marker tutorial](https://github.com/ros-visualization/visualization_tutorials/blob/indigo-devel/interactive_marker_tutorials/src/basic_controls.cpp) has multiple instances where controls are created with non-normalized rotation quaternions. Since rviz now has a stronger handling of marker quaternions [#1167](https://github.com/ros-visualization/rviz/pull/1167), this leads to errors.
Also see this [issue](https://github.com/ros-visualization/rviz/issues/1178).

**Comment by dhood** [comment]
Thank you for reporting; this was addressed by https://github.com/ros-visualization/visualization_tutorials/pull/40 (forgot to close this ticket then)
