### ISSUE TITLE
build errors on OSX

### ISSUE THREAD

**Issue by alexreg** [ros-visualization/visualization_tutorials#4]
Building rviz_plugin_tutorials on OS X 10.8.3 is yielding a linking error, it would seem. (Note: I actually run `rosmake -a --pre-clean`, having successfully followed the instructions on http://www.ros.org/wiki/groovy/Installation/OSX/Homebrew/Source#Installation_Instructions_for_Groovy_in_OSX).

```
Undefined symbols for architecture x86_64:
  "message_filters::Connection::disconnect()", referenced from:
      rviz::MessageFilterDisplay<sensor_msgs::Imu_<std::allocator<void> > >::onInitialize() in imu_display.cpp.o
      tf::MessageFilter<sensor_msgs::Imu_<std::allocator<void> > >::~MessageFilter() in imu_display.cpp.o
```

full log: http://pastie.org/pastes/7360215/text

Adding `<depend package="message_filters"/>` to the manifest.xml file for visualisation_tutorials/rviz_plugin_tutorials then gives the following.

```
Undefined symbols for architecture x86_64:
  "tf::Transformer::addTransformsChangedListener(boost::function<void ()>)", referenced from:
      tf::MessageFilter<sensor_msgs::Imu_<std::allocator<void> > >::init() in imu_display.cpp.o
```

full log: http://pastie.org/pastes/7360257/text

Now, also adding `<depend package="tf"/>` to the same manifest.xml file gives the following.

```
Undefined symbols for architecture x86_64:
  "Ogre::Quaternion::IDENTITY", referenced from:
      rviz_plugin_tutorials::ImuVisual::ImuVisual(Ogre::SceneManager*, Ogre::SceneNode*) in imu_visual.cpp.o
      rviz_plugin_tutorials::PlantFlagTool::onInitialize() in plant_flag_tool.cpp.o
      rviz_plugin_tutorials::PlantFlagTool::makeFlag(Ogre::Vector3 const&) in plant_flag_tool.cpp.o
```

full log: http://pastie.org/pastes/7360289/text

In all of the above cases this is the only package that fails to build (running `rosmake -a`) and the tail of the output looks something like this in each case:

```
[ rosmake ] Output from build of package rviz_plugin_tutorials written to:
[ rosmake ]    /Users/alex/.ros/rosmake/rosmake_output-20130408-050334/rviz_plugin_tutorials/build_output.log
[rosmake-0] Finished <<< rviz_plugin_tutorials [FAIL] [ 76.76 seconds ]                             
[ rosmake ] Halting due to failure in package rviz_plugin_tutorials. 
[ rosmake ] Waiting for other threads to complete.
[ rosmake ] Output from build of package turtle_actionlib written to:... [ 2 Active 85/88 Complete ]
[ rosmake ]    /Users/alex/.ros/rosmake/rosmake_output-20130408-050334/turtle_actionlib/build_output.log
[rosmake-1] Finished <<< turtle_actionlib [PASS] [ 56.78 seconds ] [ 3 warnings [ 1 deprecated ]  ] 
[ rosmake ] Output from build of package actionlib_tutorials written to: [ 1 Active 86/88 Complete ]
[ rosmake ]    /Users/alex/.ros/rosmake/rosmake_output-20130408-050334/actionlib_tutorials/build_output.log
[rosmake-5] Finished <<< actionlib_tutorials [PASS] [ 91.02 seconds ] [ 5 warnings  ]               
[ rosmake ] Results:                                                                                
[ rosmake ] Cleaned 88 packages.                                                                    
[ rosmake ] Built 88 packages with 1 failures.                                                      
[ rosmake ] Summary output to directory                                                             
[ rosmake ] /Users/alex/.ros/rosmake/rosmake_output-20130408-050334
```

I am unable to get rid of this last issue with "undefined symbols" however, and am not even sure my previous attempted fixes are the right way to go about it. Any help would be appreciated.

**Comment by hershwg** [comment]
In general, rviz's build file should "export" all of its dependencies to packages which depend on rviz, so they don't need to know about those dependencies.  Clearly that dependency forwarding is not working.

@wjwwood, can you reproduce this on your mac?

Looking at rviz's build file, I see

```
catkin_package(
  INCLUDE_DIRS
  src
  ${EIGEN_INCLUDE_DIRS}
  ${OGRE_INCLUDE_DIRS}
  ${OPENGL_INCLUDE_DIR}
  LIBRARIES
  rviz
  default_plugin
  ${OGRE_LIBRARIES}
  ${rviz_ADDITIONAL_LIBRARIES}
  ${OPENGL_LIBRARIES}
)
```

The "INCLUDE_DIRS" and "LIBRARIES" sections are (I believe) specifying exports, so must be for some reason those exports don't get communicated to downstream rosbuild packages.

**Comment by wjwwood** [comment]
The symbol `message_filters::Connection::disconnect`, for example, is in the `message_filters` library which rviz gets with:

```
find_package(catkin REQUIRED
  COMPONENTS
...
  message_filters
...
)
```

This puts the link flags for `message_filters` in the `catkin_LIBRARIES` and `message_filters_LIBRARIES` CMake variables, neither of which are passed to `catkin_package(LIBRARIES ...)` for export, therefore `message_filters`'s link flags are not passed along to dependent packages like `rviz_tutorials`.

Adding `catkin_LIBRARIES` to the `catkin_package(LIBRARIES ...)` call should resolve the first two, as for why there are Ogre symbols missing, I am not sure, perhaps the variable being passed to `catkin_package(LIBRARIES ...)` is not the correct one, e.g. `OGRE_LIBRARIES` vs `Ogre_LIBRARIES` vs `OGRE_LIBRARY` or something like that.

**Comment by alexreg** [comment]
Where is `catkin_package(LIBRARIES ...)`?

**Comment by wjwwood** [comment]
https://github.com/ros-visualization/rviz/blob/groovy-devel/CMakeLists.txt#L72

**Comment by alexreg** [comment]
Oh, for rviz! Should have said. ;)

**Comment by wjwwood** [comment]
Yeah, sorry this is a bug in `rviz`'s exporting of dependencies.

**Comment by alexreg** [comment]
No worries. Will test out now and report back!

**Comment by alexreg** [comment]
Okay, so testing reveals that modifying `catkin_package(LIBRARIES ...)` as you suggest does NOT fix the issue unfortunately. I kind of suspected that, since I was doubting that the CMakeLists.txt file for rviz (which is a Catkin package) would have anything to do with rosmake... So I have to do it the way I originally did (modifying the manifest.xml) for it to work.

**Comment by alexreg** [comment]
@wjwwood @hershwg Can either of you recommend a fix for now, perhaps? I'm still left with the error related to undefined symbols concerning Ogre... Would much appreciate a temporary fix, or even some hints. Thansk.

**Comment by wjwwood** [comment]
@alexreg I'll try to fix this today or tomorrow, but I can't promise anything.

**Comment by alexreg** [comment]
Okay, that would be great if you could, cheers.

**Comment by hershwg** [comment]
@alexreg, does this https://github.com/ros-visualization/visualization_tutorials/commit/5d70c1a97c50c7ae932f78058172288561fe3ccb change make it work for you?  I don't have a mac to test it on, but this just explicitly pulls in OGRE includes and library linkage.  (That branch does not include the other manifest.xml changes you mentioned, so you may want to cherry-pick this commit into your working copy.)

**Comment by alexreg** [comment]
@hershwg No luck I'm afraid... exactly the same error. (Incidentally I just applied that patch to the single file.) Thanks for the suggestion though.

**Comment by dgossow** [comment]
You will need to actually link against the Ogre libraries:

```
target_link_libraries(${PROJECT_NAME} ${QT_LIBRARIES} ${OGRE_LIBRARIES})
```

**Comment by alexreg** [comment]
Thanks @dgossow; that does the trick!

To anyone else making this fix, note that you still need to modify the manifest.xml file by adding:

```
<depend package="class_loader"/>
<depend package="message_filters"/>
<depend package="tf"/>
```

Then everything should build fine!

**Comment by dgossow** [comment]
@hershwg Please review and merge once you come back.

**Comment by hershwg** [comment]
Fixed by @dgossow 's pull request.
