### ISSUE TITLE
Release into Melodic

### ISSUE THREAD

**Issue by clalancette** [ros-visualization/visualization_tutorials#45]
All of the dependencies for this package are available in Melodic, so it would be great to get it released.  Thanks in advance!

**Comment by clalancette** [comment]
Ping, can we get this released into Melodic?  Thanks.

**Comment by wjwwood** [comment]
https://github.com/ros/rosdistro/pull/17795 👍

**Comment by clalancette** [comment]
Thanks @wjwwood
