### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Ircbarros** [ros-visualization/visualization_tutorials#51]
I'm facing the error:

Traceback (most recent call last):
  File "/home/ircbarros/Desktop/LaserGUI/main/librviz.py", line 23, in <module>
    import rviz
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rviz/__init__.py", line 19, in <module>
    import librviz_shiboken
ImportError: No module named librviz_shiboken

When i try to run the rviz_python_tutorial

**Comment by wjwwood** [comment]
Sorry for not reply to this, but Indigo is EOL so we don't support it any longer. I think this is the same issue as https://github.com/ros-visualization/visualization_tutorials/issues/52.

If it is still an issue in Kinetic, Melodic, or Noetic I'll have a look, but I didn't see it yet.

**Comment by dalatony** [comment]
I am facing the same problem, anyone got the solution yet?

**Comment by JuliusSustarevas** [comment]
same , my suspicion is that PySide support was removed for rviz at some point and not put back. There is something about it change logs. 

But this is def still happening on melodic
