### ISSUE TITLE
ImportError: No module named librviz_shiboken

### ISSUE THREAD

**Issue by anubhav1772** [ros-visualization/visualization_tutorials#52]
When I am trying to run `myviz.py` file inside `rviz_python_tutorial` package using
 `rosrun rviz_python_tutorial myviz.py` command, I am getting below error:
`ImportError: No module named librviz_shiboken`. 

Do I have to install some libraries in order to import `librviz_shiboken`? You help/guidance will be much appreciated. Thanks!

**Comment by wjwwood** [comment]
Sorry for not reply to this, what version of ROS? What Operating System?

I'll close this for now, since it stale, but I'll reopen if this is still an issue for you.

**Comment by dalatony** [comment]
I am facing the same problem, anyone got the solution yet?
ImportError: cannot import name 'librviz_shiboken'
