### ISSUE TITLE
plugin_description malformed

### ISSUE THREAD

**Issue by dgossow** [ros-visualization/visualization_tutorials#9]
The plugin_description.xml file seems to have an issue which generates error messages when running rviz in hydro.

See https://github.com/ros-visualization/rviz/issues/660

**Comment by hershwg** [comment]
Looks like the problem with the plugin tutorial is that the cmake file does not install the XML file. The problem with the python tutorial is that the package.xml file promises that there will be an XML file but none exists or is needed.  The Python error can be ignored and the plugin error will go away if you build the tutorial from source.

Still 2 valid bugs that need to be fixed the though, thanks.
